---
# this is necessary because ansible_user becomes unset in become_user clauses
- name: Get actual user
  set_fact:
    actual_user: "{{ ansible_user }}" 

- name: Get actual user Home
  shell: >
    getent passwd {{ actual_user }} | cut -d: -f6
  changed_when: false
  register: actual_user_home

- name: Install pipenv
  become_user: "{{ actual_user }}"
  pip:
    name: pipenv
    extra_args: --user

- name: Ensure pip --user enabled in .bashrc
  become_user: "{{ actual_user }}"
  blockinfile:
    dest: "{{ actual_user_home }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pip"
    block: |
      [[ -d $HOME/.local/bin ]] && {
        PATH="$HOME/.local/bin:$PATH"
      }

